# Generated by Django 2.2 on 2020-03-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'sermon', 'verbose_name_plural': 'Sermons'},
        ),
    ]
